# Generated by Django 5.0.6 on 2024-05-12 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='desc',
        ),
    ]
