# Generated by Django 4.1.13 on 2024-09-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='blog/'),
            preserve_default=False,
        ),
    ]
